### ISSUE TITLE
Full Stack JS Techdegree Projectsto be Completed

### ISSUE THREAD

**Issue by fallencloud** [fallencloud/Full_stack_conf#2]
## TODO

*Courses left to complete the Treehouse Full Stack JavaScript TechDegree*

- [ ] Project 7: Build a Twitter Interface
- [ ] Project 8: Using Gulp to Build a Front End Website 
- [ ] Project 9: Create a Gallery App with React 
- [ ] Project 10: Build a Library Manager
- [ ] Project 11: Build a Course Rating API With Express
- [ ] Project 12: Capstone Project: Build Your Own Web Application

:tada: 🙆 🎊 

cc @fallencloud
